import * as THREE from 'three';
const $=s=>document.querySelector(s),embedded=window.parent!==window,STORE_KEY='cheung-chau-claw-prizes-v2';
let config,credits=0,collection=[],state='loading',direction=0,clawX=0,scene,camera,renderer,clock,machine,claw,cable,arms=[],toyMeshes=[],heldToy=null,lockedCredits=false;
const tweens=[],pointer={x:0,y:0},palette=[0xd85c45,0x5d9c9b,0xe0a34d,0x8da9b7,0x9e6250,0xe8c758];
function incomingScore(fallback){const raw=new URLSearchParams(location.search).get('score');if(raw!==null&&raw!==''&&Number.isFinite(+raw))return +raw;if(Number.isFinite(window.__islandScore))return +window.__islandScore;return fallback}
function report(done=false){if(embedded)window.parent.postMessage({type:'island-stats',set:{score:credits,clawPrizes:collection},complete:done},'*');else localStorage.setItem(STORE_KEY,JSON.stringify(collection))}
window.addEventListener('message',e=>{const d=e.data;if(!d||d.type!=='island-stats')return;if(d.request==='dump')return report(false);if(Number.isFinite(+d.score)&&state==='idle'&&!lockedCredits){credits=+d.score;updateHud()}if(Array.isArray(d.clawPrizes)){collection=d.clawPrizes;updateHud()}});
function mat(color,metal=.05,rough=.55,opts={}){return new THREE.MeshStandardMaterial({color,metalness:metal,roughness:rough,...opts})}
function mesh(geometry,material,parent=scene){const m=new THREE.Mesh(geometry,material);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function box(w,h,d,color,parent=scene,x=0,y=0,z=0,metal=.1){const m=mesh(new THREE.BoxGeometry(w,h,d),mat(color,metal,.42),parent);m.position.set(x,y,z);return m}
function cylinder(r,h,color,parent=scene){return mesh(new THREE.CylinderGeometry(r,r,h,18),mat(color,.5,.28),parent)}
function buildScene(){scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x08252d,.033);camera=new THREE.PerspectiveCamera(34,innerWidth/innerHeight,.1,100);camera.position.set(0,3.2,18);renderer=new THREE.WebGLRenderer({canvas:$('#scene'),alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;scene.add(new THREE.HemisphereLight(0xffe6b0,0x09232c,2.1));const key=new THREE.SpotLight(0xffc46b,85,30,.55,.6,1.2);key.position.set(3,11,8);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key);const fill=new THREE.PointLight(0x4ad4d5,28,20);fill.position.set(-7,4,6);scene.add(fill);buildMachine();spawnToys();window.addEventListener('resize',resize);window.addEventListener('pointermove',e=>{pointer.x=e.clientX/innerWidth-.5;pointer.y=e.clientY/innerHeight-.5});clock=new THREE.Clock();animate()}
function buildMachine(){machine=new THREE.Group();machine.position.set(2.2,.1,0);scene.add(machine);const red=0x9e3328,gold=0xdcae55,dark=0x102b31;box(9.7,.75,3.2,red,machine,0,5.4,0,.25);box(9.5,1.65,3.1,red,machine,0,-4.45,0,.2);box(.45,9.2,.42,gold,machine,-4.7,.45,1.25,.65);box(.45,9.2,.42,gold,machine,4.7,.45,1.25,.65);box(9.85,.38,.42,gold,machine,0,4.95,1.25,.65);box(9.85,.38,.42,gold,machine,0,-3.55,1.25,.65);box(9.25,.35,2.8,dark,machine,0,-3.4,0,.25);const back=box(9.1,8.1,.12,0x12353c,machine,0,.55,-1.45,.05);back.material.emissive=new THREE.Color(0x061a20);back.material.emissiveIntensity=.6;const glassMat=new THREE.MeshPhysicalMaterial({color:0x9de8ed,transparent:true,opacity:.13,roughness:.08,metalness:0,transmission:.72,thickness:.15,side:THREE.DoubleSide});const glass=mesh(new THREE.PlaneGeometry(9.1,8),glassMat,machine);glass.position.set(0,.6,1.43);box(2.25,1.05,.55,0x09171b,machine,-3.15,-4.2,1.25,.5);box(1.7,.12,.62,gold,machine,-3.15,-3.72,1.27,.6);for(let i=0;i<12;i++){const bulb=mesh(new THREE.SphereGeometry(.08,10,8),new THREE.MeshStandardMaterial({color:0xffdf83,emissive:0xff9b38,emissiveIntensity:4}),machine);bulb.position.set(-4.35+i*.79,5.37,1.63)}box(8.3,.16,.18,gold,machine,0,4.2,.35,.8);claw=new THREE.Group();machine.add(claw);claw.position.set(0,4.05,.45);box(.72,.42,.65,red,claw,0,0,0,.5);cable=cylinder(.035,2.1,0xe8d9b0,claw);cable.position.y=-1.2;const hub=cylinder(.28,.35,0xd8aa53,claw);hub.rotation.z=Math.PI/2;hub.position.y=-2.3;for(const side of [-1,1]){const pivot=new THREE.Group();pivot.position.set(side*.16,-2.34,0);claw.add(pivot);const arm=cylinder(.055,1.05,0xe1c16c,pivot);arm.position.y=-.48;arm.rotation.z=side*.28;const tip=mesh(new THREE.SphereGeometry(.1,12,8),mat(0xc23f31,.35,.3),pivot);tip.position.set(-side*.14,-.98,0);arms.push({pivot,side})}}
function createToy(prize,index){const group=new THREE.Group(),color=palette[index%palette.length],bodyMat=mat(color,.05,.68),cream=mat(0xf3d8a4,0,.8);const body=mesh(new THREE.SphereGeometry(.58,28,22),bodyMat,group);body.scale.set(.9,1.08,.82);body.position.y=.52;const head=mesh(new THREE.SphereGeometry(.52,28,22),bodyMat,group);head.position.y=1.25;for(const side of [-1,1]){const ear=mesh(new THREE.SphereGeometry(.25,20,14),bodyMat,group);ear.position.set(side*.39,1.58,0);ear.scale.set(.8,1,.65)}const muzzle=mesh(new THREE.SphereGeometry(.25,20,14),cream,group);muzzle.position.set(0,1.18,.43);muzzle.scale.set(1,.7,.45);for(const side of [-1,1]){const eye=mesh(new THREE.SphereGeometry(.047,12,8),mat(0x171415,0,.25),group);eye.position.set(side*.17,1.4,.48)}const badge=mesh(new THREE.CylinderGeometry(.16,.16,.035,20),mat(0xf0c65e,.4,.28),group);badge.rotation.x=Math.PI/2;badge.position.set(0,.55,.49);group.userData={prize,index};machine.add(group);return group}
function spawnToys(){toyMeshes.forEach(t=>machine.remove(t));toyMeshes=[];const positions=[[-3.6,-2.6,-.45],[-2.25,-2.48,.2],[-.9,-2.6,-.5],[.45,-2.52,.15],[1.85,-2.6,-.35],[3.25,-2.48,.05],[-2.9,-1.35,-.8],[-1.55,-1.3,-.25],[-.15,-1.4,-.75],[1.25,-1.32,-.2],[2.65,-1.4,-.7]];positions.forEach((p,i)=>{const prize=config.prizes[i%config.prizes.length],toy=createToy(prize,i);toy.position.set(...p);toy.rotation.y=(i%4-1.5)*.18;toy.rotation.z=(i%3-1)*.08;toy.userData.home=toy.position.clone();toyMeshes.push(toy)})}
function tween(object,to,duration,ease=t=>1-Math.pow(1-t,3)){return new Promise(resolve=>tweens.push({object,from:Object.fromEntries(Object.keys(to).map(k=>[k,object[k]])),to,duration,start:performance.now(),ease,resolve}))}
function updateTweens(now){for(let i=tweens.length-1;i>=0;i--){const t=tweens[i],p=Math.min(1,(now-t.start)/t.duration),e=t.ease(p);Object.keys(t.to).forEach(k=>t.object[k]=t.from[k]+(t.to[k]-t.from[k])*e);if(p>=1){tweens.splice(i,1);t.resolve()}}}
function animate(now=0){requestAnimationFrame(animate);updateTweens(now);if(state==='aiming'&&direction){clawX=THREE.MathUtils.clamp(clawX+direction*.055,-3.7,3.7);claw.position.x=clawX}if(heldToy){heldToy.position.x=claw.position.x;heldToy.position.y=claw.position.y-2.95;heldToy.position.z=claw.position.z}const t=clock.getElapsedTime();machine.rotation.y=Math.sin(t*.22)*.012;camera.position.x=pointer.x*.45;camera.position.y=3.2-pointer.y*.24;camera.lookAt(1.2,.25,0);renderer.render(scene,camera)}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
function updateHud(){$('#balance').textContent=credits;$('#collectionCount').textContent=collection.length}
function setStatus(label,message,strength=0){$('#roundLabel').textContent=label;$('#message').textContent=message;$('#strengthFill').style.width=strength+'%'}
function setControls(on){['left','right','drop'].forEach(id=>$('#'+id).disabled=!on)}
function resetClaw(){clawX=0;claw.position.set(0,4.05,.45);cable.scale.y=1;arms.forEach(a=>a.pivot.rotation.z=0);heldToy=null}
function begin(){const cost=+config.settings.playCost||200;if(credits<cost){$('#startMessage').textContent=`分數不足，需要 ${cost} 分。`;return}credits-=cost;lockedCredits=true;updateHud();report(false);$('#startModal').classList.add('hidden');$('#resultModal').classList.add('hidden');spawnToys();resetClaw();state='aiming';setControls(true);setStatus('POSITIONING','按住左右移動，對準公仔重心',35)}
async function drop(){if(state!=='aiming')return;state='dropping';direction=0;setControls(false);setStatus('CLAW DESCENDING','落爪中…',55);await Promise.all([tween(claw.position,{y:.35},1050),tween(cable.scale,{y:4.45},1050)]);arms.forEach(a=>a.pivot.rotation.z=-a.side*.48);await wait(360);const nearest=toyMeshes.filter(t=>t.position.y<-.6).sort((a,b)=>Math.abs(a.position.x-clawX)-Math.abs(b.position.x-clawX))[0],distance=nearest?Math.abs(nearest.position.x-clawX):99,accuracy=Math.max(0,1-distance/1.05),grip=nearest?.userData.prize.grip??0,chance=accuracy*(.62+grip*.38),success=distance<1.05&&Math.random()<chance;setStatus(success?'GRIP LOCKED':'GRIP SLIPPING',success?'夾爪扣住公仔！':'重心未對準，公仔滑開…',Math.round(chance*100));if(success){heldToy=nearest;nearest.position.y=claw.position.y-2.95}await wait(250);await Promise.all([tween(claw.position,{y:4.05},1150),tween(cable.scale,{y:1},1150)]);if(success){await tween(claw.position,{x:-3.15},900);clawX=-3.15;heldToy=null;await tween(nearest.position,{y:-4.35,z:1.15},620,t=>t*t);nearest.scale.setScalar(.35);win(nearest.userData.prize)}else lose()}
function win(prize){state='result';collection.unshift({id:prize.id,name:prize.name,rarity:prize.rarity,time:Date.now()});updateHud();report(false);$('#resultEyebrow').textContent='PRIZE CAPTURED';$('#resultPreview').textContent=prize.emoji||'🧸';$('#resultTitle').textContent=`成功夾到「${prize.name}」`;$('#resultText').textContent=`準繩落爪！${prize.rarity}已跌入取物口。`;$('#resultModal').classList.remove('hidden');setStatus('PRIZE GET',`已獲得 ${prize.name}`,100)}
function lose(){state='result';$('#resultEyebrow').textContent='SO CLOSE';$('#resultPreview').textContent='🕹️';$('#resultTitle').textContent='差一點就夾到了';$('#resultText').textContent='留意公仔的立體位置與重心，再調整夾爪。';$('#resultModal').classList.remove('hidden');setStatus('MISS','公仔跌回機內',18)}
function openStart(){state='idle';direction=0;setControls(false);resetClaw();$('#resultModal').classList.add('hidden');$('#startModal').classList.remove('hidden');$('#startMessage').textContent='';$('#start').textContent=`投入 ${config.settings.playCost} 分`;setStatus('READY',`每次遊戲 ${config.settings.playCost} 分`,0)}
function move(dir){if(state==='aiming')direction=dir}function stop(){direction=0}function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function bindHold(id,dir){const el=$('#'+id);el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);move(dir)});['pointerup','pointercancel','lostpointercapture'].forEach(n=>el.addEventListener(n,stop))}
bindHold('left',-1);bindHold('right',1);$('#drop').onclick=drop;$('#start').onclick=begin;$('#again').onclick=openStart;$('#close').onclick=()=>$('#resultModal').classList.add('hidden');$('#returnStory').onclick=()=>report(true);document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.code==='Space'){e.preventDefault();drop()}});document.addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight')stop()});
try{config=await(await fetch('config.json',{cache:'no-store'})).json();credits=incomingScore(config.settings.startingCredits);if(!embedded)try{collection=JSON.parse(localStorage.getItem(STORE_KEY)||'[]')}catch{}updateHud();buildScene();openStart();setTimeout(()=>$('#loading').classList.add('done'),450)}catch(error){$('#loading span').textContent='3D 機台載入失敗，請重新整理。';console.error(error)}
