const $=s=>document.querySelector(s),embedded=window.parent!==window,STORE_KEY='cheung-chau-claw-prizes-v1';
let config,credits=0,state='idle',x=50,raf=0,direction=0,prizes=[],collection=[],lockedCredits=false;
function incomingScore(fallback){const raw=new URLSearchParams(location.search).get('score');if(raw!==null&&raw!==''&&Number.isFinite(+raw))return +raw;if(Number.isFinite(window.__islandScore))return +window.__islandScore;return fallback}
function report(done=false){if(embedded)window.parent.postMessage({type:'island-stats',set:{score:credits,clawPrizes:collection},complete:done},'*');else localStorage.setItem(STORE_KEY,JSON.stringify(collection))}
window.addEventListener('message',e=>{const d=e.data;if(!d||d.type!=='island-stats')return;if(d.request==='dump')return report(false);if(Number.isFinite(+d.score)&&state==='idle'&&!lockedCredits){credits=+d.score;$('#balance').textContent=credits}if(Array.isArray(d.clawPrizes))collection=d.clawPrizes});
function toyMarkup(prize,extra=''){return `<div class="toy ${extra}" data-id="${prize.id}" style="--toy:${prize.color}"><i class="toy-body"></i><i class="toy-face"></i><b class="toy-label">${prize.name}</b></div>`}
function seedPrizes(){const field=$('#prizeField');field.innerHTML='';prizes=[];const slots=[12,25,38,51,64,77,88,18,33,47,61,73,84];slots.forEach((left,i)=>{const prize=config.prizes[i%config.prizes.length],top=i<7?72:48+(i%2)*7,el=document.createElement('div');el.innerHTML=toyMarkup(prize);const toy=el.firstElementChild;toy.style.left=left+'%';toy.style.top=top+'%';toy.style.transform=`translate(-50%,-50%) rotate(${(i%5-2)*7}deg)`;field.append(toy);prizes.push({prize,el:toy,x:left,top})})}
function setControls(enabled){['left','right','drop'].forEach(id=>$('#'+id).disabled=!enabled)}
function updateMessage(label,message){$('#roundLabel').textContent=label;$('#message').textContent=message}
function begin(){const cost=+config.settings.playCost||200;if(credits<cost){$('#startMessage').textContent=`分數不足，需要 ${cost} 分。`;return}credits-=cost;lockedCredits=true;$('#balance').textContent=credits;report(false);$('#startModal').classList.add('hidden');$('#resultModal').classList.add('hidden');state='aiming';x=50;$('#carriage').style.left=x+'%';seedPrizes();setControls(true);updateMessage('移動夾爪','按住 ← → 對準你想要的公仔');loop()}
function loop(){if(state==='aiming'&&direction){x=Math.max(6,Math.min(94,x+direction*(+config.settings.moveSpeed||.72)));$('#carriage').style.left=x+'%'}raf=requestAnimationFrame(loop)}
function move(dir){if(state==='aiming')direction=dir}function stop(){direction=0}
async function drop(){if(state!=='aiming')return;state='dropping';direction=0;setControls(false);updateMessage('落爪中','夾爪正在下降……');const carriage=$('#carriage'),claw=$('#claw');carriage.classList.add('down');await wait(800);claw.classList.add('closed');await wait(420);const range=+config.settings.grabRange||7.5,candidates=prizes.filter(p=>!p.el.classList.contains('won')&&Math.abs(p.x-x)<=range).sort((a,b)=>Math.abs(a.x-x)-Math.abs(b.x-x)),target=candidates[0],success=!!target&&Math.random()<target.prize.grip;if(success){target.el.classList.add('grabbed');target.el.style.left=x+'%';target.el.style.top='7%'}else updateMessage('差少少！','夾爪滑開了……');await wait(250);carriage.classList.remove('down');await wait(850);if(success){target.el.classList.add('won');await wait(650);win(target.prize)}else lose()}
function win(prize){state='result';collection.unshift({id:prize.id,name:prize.name,rarity:prize.rarity,time:Date.now()});report(false);$('#resultEyebrow').textContent='PRIZE GET';$('#resultTitle').textContent=`夾到「${prize.name}」！`;$('#resultText').textContent=`${prize.rarity}已經跌入取物口。`;$('#resultToy').innerHTML=toyMarkup(prize);$('#resultModal').classList.remove('hidden');updateMessage('成功！',`你帶走了 ${prize.name}`)}
function lose(){state='result';$('#resultEyebrow').textContent='SO CLOSE';$('#resultTitle').textContent='今次差少少！';$('#resultText').textContent='重新觀察公仔重心，再試一次。';$('#resultToy').innerHTML='';$('#resultModal').classList.remove('hidden');updateMessage('未能抓住','公仔跌回機內')}
function wait(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
function openStart(){state='idle';cancelAnimationFrame(raf);direction=0;$('#claw').classList.remove('closed');$('#carriage').classList.remove('down');$('#resultModal').classList.add('hidden');$('#startMessage').textContent='';$('#startModal').classList.remove('hidden');$('#start').textContent=`投入 ${config.settings.playCost} 分開始`;setControls(false)}
function bindHold(id,dir){const el=$('#'+id);['pointerdown','touchstart'].forEach(name=>el.addEventListener(name,e=>{e.preventDefault();move(dir)},{passive:false}));['pointerup','pointercancel','pointerleave','touchend'].forEach(name=>el.addEventListener(name,stop))}
bindHold('left',-1);bindHold('right',1);$('#drop').onclick=drop;$('#start').onclick=begin;$('#again').onclick=openStart;$('#close').onclick=()=>$('#resultModal').classList.add('hidden');$('#returnStory').onclick=()=>report(true);document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1);if(e.code==='Space'){e.preventDefault();drop()}});document.addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight')stop()});
(async()=>{config=await(await fetch('config.json',{cache:'no-store'})).json();credits=incomingScore(config.settings.startingCredits);if(!embedded)try{collection=JSON.parse(localStorage.getItem(STORE_KEY)||'[]')}catch{}$('#balance').textContent=credits;seedPrizes();openStart()})();
